# pnpm-workspace.yaml
packages:
  # Standard packages
  - 'packages/*'
  # Apps
  - 'apps/*'
  # Supabase functions (for sharing types)
  - 'supabase/functions'
  # exclude packages that are inside test directories
  - '!**/test/**' 